---
title: "Application"
description: |
 Things you must check before applying and how to apply
---

<span style="background-color: #FFFF00">All links to NTU websitelink automatically to the Chinese version of the homepage. I could not fix this issue for now, but still want to try becaus this will be much better than just write go the NTU website</span>

Overseas students applying to NTU are divided into **International Students**, **Overseas Chinese Students**, **Hong Kong and Macao Students**, and **Mainland Chinese Students**. The application process, tuition fees, and available degrees may differ depending on students' identities. Before you start your application to NTU, it is important to check your **[eligibility](https://oia.ntu.edu.tw/apply-to-ntu/degree-student/eligibility)** and decide the application methods you would like to use to submit your application (check important Note for students from Mainland China available on the same page).

International applicants with a **Bachelor's degree** should be eligible to apply to our Master’s Degree program; in addition, candidate are strongly advised **to contact possible tutor** prior their application in order to discuss the relevance of the research topics he wants to develop. Candidates with strong motivation and a certain scientific maturity will be an advantage at the selection of elligible applications.

Once you checked your eligibility, contact a possible advisor, you should decide your the time you want to join our master. The first semester classes start in September and second semester classes start in February. At IONTU we request master students to start at <span style="background-color: #FFFF00">the first semester in September</span>. On the same page you checked your [eligibility](https://oia.ntu.edu.tw/apply-to-ntu/degree-student/eligibility), open the link to **September Entry**. 

1. You find in the section *Before Applying* an online document you must read carefully **Admission Guidelines for International Degree Students** and another link to check the [scholarships](https://oia.ntu.edu.tw/prospective-students/study-at-ntu-vvh9/scholarships) you can applied for. 

2. In the section *Program Requirements*, you will find important information about the admission quota on foreign applicants and [specific requirements](http://oiasystem.ntu.edu.tw/admission/foreign/requirement/dept.detail/id/38/degree/M/sn/1321) related to our program. Two rounds of application are possible to enter our program in September (see specific dates for the applications at the bottom of the same webpage)

3. The section *How to Apply* provides links to the **Online Application System for International Degree Students**. Click **Apply Now** and follow the instruction after you make sure you have all required documents ready. 