---
title: "Optional courses"
description: |
 List of optional courses in English and by topic
---

Those classes are optional. You must accumulated a minimum of **13 credits** with these classes on the **24 credits** you need to get your  degree and aside from your thesis.


## General Topics

Those courses ...


<details>
<summary><span style="color:#1D5287">**English Writing in Marine Sciences**</span> ([OCEAN 7168]()) - 3 credits</summary>
**Description**: this seminar course is designed to improve IONTU graduate students’ communication skills through writing in English. Students will utilize examples from the textbook, “Writing science: How to write papers that get cited and proposals that get funded” by Joshua Schimel. I will also share comments and revisions to scientific manuscripts that I collected over the years. The class starts by having students write a short Facebook post about their own research. Students will lean to expand their Facebook post into a one-page-long (800-850 words) article. Throughout the class, students will apply writing styles and techniques to edit their article, including ways to condense their article to only 300-350 word long. Each student is also required to read and analyze four published scientific papers of their own choice: one from a specialist journal written by a leader recognized in their field and a good writer, one typical paper from a specialized journal, one review paper, and one article from Nature or Science. The course will also incorporate peer-review practices; students will learn to recognize strengths and weakness of other students’ writing and give constructive comments to help improve each other’s writing. This is exactly what scientists do routinely: we review and give constructive comments to other’s manuscripts and proposals to help the science community grow. Students who have already had writing projects (such as an abstract, manuscript, or dissertation) can also practice analyzing and editing these drafts. We will also invite a guest lecturer from NTU’s Department of Foreign Languages and Literature or from NTNU’s English Department to talk about common English mistakes made by Taiwanese students and ways to improve this.

**Instructor**: Huei-Ting (Tina) Lin

</details>

## Marine Biology and Ecology

Those courses ...

<details>
<summary><span style="color:#1D5287">**Field Course in Coral Reef Ecology**</span> ([OCEAN 7194]()) - 3 credits</summary>
**Description**: this course is designed to provide the student with a solid foundation in ecological concepts, techniques and experimental design in field research as applied to coral reef ecosystems. It consists of a one-week field-based research at a marine research station in Taiwan. To have attended Ocean 5097 is strongly recommended before joining this course. Alternatively, solid knowledge of coral reefs and the environmental challenges they are currently facing is requested. The course will begin with a general introduction of the coral reefs and how they are influenced by global and local factors. It will quickly narrow down to the context of Taiwan by introducing the local context: known diversity, past disturbances, and on-going research. The major reef biota will be discussed in terms of their ecological requirements, roles on the reef and their overall impact. Methods in ecological monitoring and sampling will be discussed and applied on the field and will serve as a baseline for a future long-term ecological assessment. Data analysis will consist of examining and comparing structure of benthic assemblages among sites and depths (basic knowledge of R software is recommended). Students are asked to provide a poster (electronic format) summarizing their work a maximum of one month after the last day on the field. 

**Instructor**: Vianney DENIS
</details>

<details>
<summary><span style="color:#1D5287">**Coral Reef Ecosystem in a Changing World**</span> ([OCEAN 5097]()) - 3 credits</summary>
**Description**: The rapid decline of coral reefs around the world motivates research to better understand how this complex ecosystem will respond to future environmental changes. This course will review current knowledge on reef organisms and coral reef ecosystem, and will study the factors responsible for reef degradation. The basic elements to assess resilience of this ecosystem will be introduced. The students will learn how the knowledge and skills obtained through the lectures and practice work can be used for the management and the conservation of this fragile ecosystem.

**Instructor**: Vianney DENIS
</details>

<details>
<summary><span style="color:#1D5287">**Special topics on Ichthyology**</span> ([OCEAN 5067]()) - 2 credits</summary>
**Description**: This course provides advanced information on fishes. The contents incorporate the latest advances in the biology of fishes, mainly covering taxonomy, physiology, biogeography, ecology, behavior and conservation of fishes.

**Instructor**: Jen-Chieh SHIAO
</details>

<details>
<summary><span style="color:#1D5287">**Special Topic-fish Physiology and Ecology (1)**</span> ([OCEAN 7141]()) - 1 credits</summary>
**Description**: In this course, students are requested to read the scientific papers related to fish physiology and ecology and brief present the paper contents. Other students are requested to join the discussion based on the paper presented by the students.

**Instructor**: Jen-Chieh SHIAO
</details>

<details>
<summary><span style="color:#1D5287">**Special Topic-fish Physiology and Ecology (2)**</span> ([OCEAN 7144]()) - 1 credits</summary>
**Description**: In this course, students are requested to read the scientific papers related to fish physiology and ecology and brief present the paper contents. Other students are requested to join the discussion based on the paper presented by the students.

**Instructor**: Jen-Chieh SHIAO
</details>

<details>
<summary><span style="color:#1D5287">**Fish Sclerochronology**</span> ([OCEAN 5048]()) - 1 credit

</summary>
**Description**: Students taking this course will learn the knowledge of fish hard structure and their application in age, growth, life history and the basic concepts of aged based fishery stock assessments.

**Instructor**: Jen-Chieh SHIAO
</details>

## Fisheries

<details>
<summary><span style="color:#1D5287">**Population Ecology and Sustainable Fisheries Resources**</span> ([OCEAN 5105]()) - 3 credits</summary>
**Description**: Understanding dynamics and fluctuations of natural fish populations requires a diverse set of skills. Through this course students will learn knowledge of fish biology and field and quantitative methodologies for exploring population dynamics of both freshwater and marine fishes. In addition, students will broaden understanding of fisheries and natural resource management (through lectures and text book readings), practice and develop critical thinking skills (through in-class discussions and a group presentation), and learn how to read and interpret the scientific literature in fish ecology and fisheries science (through discussing the primary literature). Ultimately, this course will provide knowledge and training on formulating research questions and tackling problems in management of fisheries and other natural resources in a changing world. 
 
**Instructor**: Hui-Yu WANG; Yi-Jay CHANG
</details>


<details>
<summary><span style="color:#1D5287">**Special Topic-Fisheries Stock Assessment (I)**</span> ([OCEAN 5111]()) - 1 credit</summary>
**Description**: These two courses (one for each semester) were designed for graduate students to keep up to date with the latest research topics and developments in fisheries stock
assessment. The course materials are mainly based on published papers in international journals. For example, papers related to fish population dynamics, stock assessment, fishery management, statistical models, and computer simulations are the primary topics of this course. Selected students give a weekly PowerPoint presentation of a paper and lead a group discussion with the professor and other students.
 
**Instructor**: Yi-Jay CHANG
</details>

<details>
<summary><span style="color:#1D5287">**Special Topic-Fisheries Stock Assessment (II)**</span> ([OCEAN 5109]()) - 1 credit</summary>
**Description**: These two courses (one for each semester) were designed for graduate students to keep up to date with the latest research topics and developments in fisheries stock
assessment. The course materials are mainly based on published papers in international journals. For example, papers related to fish population dynamics, stock assessment, fishery management, statistical models, and computer simulations are the primary topics of this course. Selected students give a weekly PowerPoint presentation of a paper and lead a group discussion with the professor and other students.
 
**Instructor**: Yi-Jay CHANG
</details>


<details>
<summary><span style="color:#1D5287">**Advanced Quantitative Methods in Fisheries Stock Assessment**</span> ([Ocean 7178]()) - 3 credits</summary>

**Description**: This course introduces advanced quantitative methods in fisheries stock assessment, including decision analysis to evaluate alternative management actions, Bayesian state-space modelling, meta-analysis, and integrated analysis. The course draws examples from real fisheries in the world and provides student broad experience with various fishery data and fish biology. The goals of this course are to train the students to be familiar with methods in fish population dynamics and stock assessment and proficient in parameter estimation, as well as the uncertainty, of an exploited fish population, and evaluation of harvest restrictions for fisheries management problems by using various computer programs and tools.
 
**Instructor**: Yi-Jay CHANG
</details>


<details>
<summary><span style="color:#1D5287">**Ecological Modeling Seminar**</span> ([Ocean 7152]()) - 2 credits</summary>

**Description**: A seminar course for presenting and discussing about research in ecology and quantitative analysis. Students are required to give 2 presentations and participate discussion in English.
 
**Instructor**: Hui-Yu WANG; Chih-Hao HSIEH
</details>


## Marine Data Analysis

<details>
<summary><span style="color:#1D5287">**Ecological Data Analysis in R**</span> ([OCEAN 5089]()) - 3 credits</summary>
**Description**: this course is designed to teach the use of a programming language for the analysis of ecological data. The course will introduce the basics of R language, and will go through topics such as data manipulation, exploration and visualization. It will then present common approaches for data analysis introducing frequent statistical tests, linear models, clustering and ordination approaches applying to multivariate data. This course mainly targets students without prior understanding of R language and who want to get familiar with this free & open-source software environment. Students will also be introduced to GitHub and Rmarkdown that further improve the use of R. Students will require a laptop for sessions. Schedule is subject to changes according to student progress.

**Instructor**: Vianney DENIS
</details>

<details>
<summary><span style="color:#1D5287">**Biological modeling**</span> ([OCEAN 5074]()) - 3 credits</summary>
**Description**: The course material is designed to be interdisciplinary, integrating biology, ecology, mathematics and environmental sciences. While the main course material is based on classic ecological modeling textbooks and articles, these analytic methods are applicable to multi-faceted research questions. The material builds from a single population and then extends to the ecosystem level, including species interaction, climate changes and disease as well as molecules interactions within cells. Regular modeling exercises are required (1 unit as practice). After equipped with modeling skills, students have to develop their own research questions and use modeling and data mining approaches to solve their questions. Instructors will guide students through the question-solving processes.

**Instructor**: Chih-hao HSIEH;  Hui-Yu WANG
</details>


<details>
<summary><span style="color:#1D5287">**Computer-Intensive Statistics in Ecology**</span> ([OCEAN 5052]()) - 3 credits</summary>
**Description**: This is an advanced course intended for senior undergraduate and graduate students with knowledge of basic statistics including random variables, analysis of variance, regression analysis, and rank-based non-parametric statistics. We will discuss several computer-intensive statistical methods. We will discuss the theory, assumption, and application of these methods in ecological problems. The course is designed for hand-on work. Students need to get familiar with at least one computer language to do the statistics. Most of work can be done with MatLab, but any other programming language will do equally well. Sometimes, we will use well-developed software when the computation is too complicated and beyond the basic level. There will be dedicated time every week for students to present their works and to discuss the application of these methods on real world problems.

**Instructor**: Chih-hao HSIEH; Yi-Jay CHANG
</details>


## Marine Geology 

## Marine Chemistry 


<details>
<summary><span style="color:#1D5287">**Environmental chemistry and sustainable management of coral reefs (field visit included)**</span> ([OCEAN 7193]()) - 3 credits</summary>
**Description**: This advanced course is designed to train graduate students and advanced undergraduate students to obtain knowledge about environmental chemistry, focusing on coral reef environmental chemistry. The students will become skillful to channel the most updated scientific research results with citizen scientists, e.g. residential volunteers. Through this course, we will search through the literature and to identify key parameters for coral reef environmental monitoring. Students will help to analyze samples collected by our collaborating citizen scientists, to interpret the data based on literature information, and to present the results to citizen scientists at the beach site at the end of the semester.

**Instructor**: Huei-Ting (Tina) Lin

## Ocean Physics

