---
title: "Required classes"
description: |
  List of required courses and by division. Classes delivered in English or with an possible alternative for foreigner students to get the corresponing credits
---

Requires classes are compulsory. They represent **11 credits on the 24 credits** you need to accumulate along the two years of your master degree. This is in addition of a Master thesis.


## Core Curriculum (all divisions) 


<details>
<summary><span style="color:#1D5287">**Fieldwork in Marine Biology**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 1 credit</summary>
**Description**: <span style="background-color: #FFFF00"> XXXX</span>

**Instructor**: <span style="background-color: #FFFF00"> XXXX</span>
</details>


<details>
<summary><span style="color:#1D5287">**Introduction to Marine Biology**</span> ([OCEAN 5038]()) - 1 credit</summary>
**Description**: This course introduces all kinds of marine organisms including phytoplankton, zooplankton, marcoagle, invertebrae, vertebrae and various and ecosystem including tidal zones, estuaries, continental shelf, coral reefs, pelgaic ocean, and deep sea. 

**Instructor**: Jen Chieh SHIAO
</details>


<details>
<summary><span style="color:#1D5287">**Physical Oceanography**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 1 credit</summary>
**Description**: <span style="background-color: #FFFF00"> XXXX</span>

**Instructor**: <span style="background-color: #FFFF00"> XXXX</span>
</details>


<details>
<summary><span style="color:#1D5287">**Introduction to Marine Geology**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 1 credit</summary>
**Description**: <span style="background-color: #FFFF00"> XXXX</span>

**Instructor**: <span style="background-color: #FFFF00"> XXXX</span>
</details>

<details>
<summary><span style="color:#1D5287">**Introduction to Marine Chemistry**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 1 credit</summary>
**Description**: <span style="background-color: #FFFF00"> XXXX</span>

**Instructor**: <span style="background-color: #FFFF00"> XXXX</span>
</details>

<details>
<summary><span style="color:#1D5287">**Fundamentals of Oceanic Statistics**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 2 credits</summary>
**Description**: <span style="background-color: #FFFF00"> XXXX</span>

**Instructor**: <span style="background-color: #FFFF00"> XXXX</span>
</details>


## Marine Biology and Fisheries


<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([OCEAN 8009]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>


<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 2**</span> ([OCEAN 8009]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: Vianney DENIS; Jen Chieh SHIAO; Wei-Jen CHEN; Yi-Jay CHANG
</details>


## Marine Geology & Geosphysics

<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>

<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>

## Chemical Oceanography

<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>

<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>

## Physical Oceanography

<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>

<details>
<summary><span style="color:#1D5287">**Seminar Master - Year 1**</span> ([<span style="background-color: #FFFF00">OCEAN XXXX</span>]()) - 4 credits (2 semesters </summary>
**Description**: Presentation of scientific paper by students

**Instructor**: <span style="background-color: #FFFF00">PENDING</span>
</details>