---
title: "Tuition fees & fellowships"
description: |
 Things you must spend, things you must get
---

NTU offers affordable tuition fees. The amount students are required to pay depends on the level of their degree, the year of their study, and the student identity, as different rates apply to International Students and Overseas Chinese, Hong Kong and Macau, and Chinese Students.For the specific cost of our Master Program accoding the category you belong, check [here](https://oia.ntu.edu.tw/prospective-students/study-at-ntu-vvh9/fees-and-financing-hpk6/tuition-fees-xkz2) at the section *Master's and PhD Degrees* and for the category **Science, Bio-resources & Agriculture, Life Science**

In addition to the tuition fees, you should consider the living cost. Despite being a modern metropolis, life in Taipei is very affordable. You will find at this [link](https://oia.ntu.edu.tw/prospective-students/study-at-ntu-vvh9/fees-and-financing-hpk6/cost-of-living-q2qx) and below an overview of the estimated cost of living per semester (in addition of tuition fees). 

**Estimated cost of living per semester:**

|
----------|-----------------------------------
**Books** | TWD 5,000 – 8,000 (USD 167 – 267)
**Housing** | On-campus double room: TWD 24,500 (USD 817)
--- | On-campus single room: TWD 37,000 (USD 1,234)
---| Off-campus: TWD 35,000 – 50,000 (USD 1,167 – 1,667)
**Insurance** | National Health Insurance (applies only to degree students): TWD 4,494 (USD 150)
**Living expenses** | TWD 50,000 (USD 1,667)
**Estimated cost of living** | TWD 84,000 – 113,000 (USD 2,800 – 3,767)



