---
title: "Coral Reef Ecosystems in a Changing World (OCEAN 5097)"
output: pdf_document
---

## Information

**Time**: Tuesday 13:20- 16:20 (Spring Semester)

**Lecturers**: Vianney DENIS

**Credits**: 3 

## References

Dai C.F., Horng S. (2009a) Scleractinia Fauna of Taiwan. I. The Complex Group. National Taiwan University.

Dai C.F., Horng S. (2009) Scleractinia Fauna of Taiwan. II. The Robust Group. National Taiwan University.

Denis V., Soto D., De Palmas S., Lin Y.T.V., Benayahu Y., et al. (2019) Taiwan. In: Loya Y., Puglise K.A., Bridge T. (eds) Mesophotic coral ecosystems. Springer, Cham. pp 249-264. doi:[10.1007/978-3-319-92735-0_14](https://link.springer.com/chapter/10.1007/978-3-319-92735-0_14)

Dubinsky Z., Stambler N. (2011) Coral Reefs: An Ecosystem in Transition. Springer, Dordrecht,552p. doi:[10.1007/978-94-007-0114-4_1](https://link.springer.com/book/10.1007%2F978-94-007-0114-4)

Sheppard C.R.C, Davy S.K., Pilling G.M., Graham N.A.J (2018) The Biology of Coral Reefs. Second Edition. Oxford University Press, 363 p. doi:[10.1093/oso/9780198787341.001.0001](https://oxford.universitypressscholarship.com/view/10.1093/acprof:oso/9780198566359.001.0001/acprof-9780198566359)  


## Outline

The rapid decline of coral reefs around the world motivates research to better understand how these ecosystems will look tomorrow under climate change. This course will make an up-to-date review of the knowledge of reef organisms and ecosystems, and it will emphasize the contemporary factors of reef degradation affecting population dynamics. Elements supporting the resilience of these ecosystems will be introduced together
with perspectives in terms of reef management. Overall, through the lectures, the students will be provided with an up-to-date understanding of the coral reef crisis and the immediate actions to take for the long-term conservation of these fragile ecosystems. Many examples will be based on reefs in Taiwan, and speakers may be invited to illustrate specific topics.

This course is an introduction to coral reefs and requires basic knowledge in marine life, biology, and ecology Few classes about coral physiology could be a bit more challenging, but overall a strong curiosity about coral reefs is the most important to enjoy this course.

## Objectives

+ Basic knowledge of reef organisms and coral ecosystems
+ Highlight research priority in the context of global changes
+ Implication for reef management and conservation


## Schedule

Topics subject to changes.

Week|Date|Content|
----|----|-------|
1|2/21|Introduction to the course
2|2/28| HOLIDAY
3|3/7|Definitions, history and future challenges in coral research
4|3/14|The paleoecology & distribution of coral reefs
5|3/21|Scleractinian coral systematics
6|3/28|Anatomy and biology of scleractinan corals
7|4/4|HOLIDAY
8|4/11|The photosynthesis of zooxanthellate corals (**Mid-term week**)
9|4/18|Coral calcification: from cells to reefs, response to ocean acidification
10|4/25|Coral reef algae: diversity, biology, ecology
11|5/2|Invertebrates and their roles in coral reef ecosystems
12|5/9|Reef fish biology and ecology
13|5/16|Acclimatization and adaptation of reef corals
14|5/23|The resilience of coral reefs and implications for reef management
15|5/30|Presentation
16|6/6|Final Exam
17| [Extra 1]
18| [Extra 2]

## Evaluation

Presence in class is compulsory. You will apply online ([myNTU](https://my.ntu.edu.tw/)) for leaves of absence.

**10%** Participation: Presence in class, questions, comments, etc. 
**20%** Quiz: Preparation + answers to the quiz 
**30%** Presentation: Scientific presentation (ppt) / research challenge 
**40%** Final exam: Essay on current issue



## Contact

vianneydenis@g.ntu.edu.tw
