---
title: "Biological Oceanography (OCEAN 5051)"
output: pdf_document
---

## Information

**Time**: Tuesday 9:10- 12:10

**Lecturers**: Chih-Hao HSIEH & Fuh-Kwo SHIAH

**Credits**: 3 

## Reference

Miller, C. B. (2004) Biological Oceanography. Blackwell Science Ltd, Oxford, U.K., 402 pp.

## Outline

This is a course intended for undergraduate and graduate students with knowledge of basic ecology. The focus will be on OCEANOGRAPHY, with investigation on interactive biological, chemical, and physical processes in the ocean. The purposes are to give an overview of biological ocean science (a wide rather than deep view) and to provide basic information and training for graduate research. The discussion will range from physical effects on the biology to biological effects on biogeochemical cycling; the spatial scale will range from individual organisms (e.g. viscosity and turbulences on plankton feeding and nutrient uptake) to ecosystem (e.g. remote sensing and circulation modeling); the organism will range from virus to whales.

## Objectives

The objectives are for students to understand how environmental effects such as ocean physics and chemistry affect organisms, across temporal and spatial scales. Further, we will explore how biological activities feedback to Earth environments, such as biogeochemical cycling and carbon flux and global climate changes.

## Schedule

Week|Content|Chapter|Lecturers
----|-------|-------|---------
1|Discussion on how to prepare final presentation & Introduction to oceanography|NA|Chih-Hao HSIEH & Fuh-Kwo SHIAH
2|The major taxa of marine planktoners w/o zooplanktoners|2|Fuh-Kwo SHIAH
3|Vertical mixing and the spring (phytoplankton) bloom|1|Fuh-Kwo SHIAH
4|Nutrient cycling: new vs. regenerated production (f-ratio)|handouts|Fuh-Kwo SHIAH
5|The ocean carbon cycle and the biological pump|3|Fuh-Kwo SHIAH
6|Particle sedimentation & dissolved organic fluxes|handouts|Fuh-Kwo SHIAH
7|Primary production |handouts|Fuh-Kwo SHIAH
8|Midterm|NA|NA
9|Marine zooplankton and their life styles|handouts|Chih-Hao HSIEH
10|Ocean instruments|handouts|Chih-Hao HSIEH
11|Foodweb dynamics and microbial loop|5|Chih-Hao HSIEH
12|Remote sensing|6|Chih-Hao HSIEH
13|Secondary production|7|Chih-Hao HSIEH
14|Population dynamics|8|Chih-Hao HSIEH
15|Coupled biological/physical modeling|4|Chih-Hao HSIEH
16|Fisheries oceanography|15|Chih-Hao HSIEH
17|Global climate change|16|Chih-Hao HSIEH
18|Final|NA|Chih-Hao HSIEH

## Evaluation

**30%** Midterm
**30%** Final
**40%** Oral presentation (a list of research topics named “Marine Ecology in the Cutting Edge” will be provided.  Biological oceanography is a multidisciplinary science, and we need to learn what other fields can help us to understand our ocean.  For example, how engineer help design sampling devices that are useful in collecting biological data.  Each student is required to pick a topic from the list and give a presentation on that topic.Suitable references will be provided)




       
