---
title: "Computer intensive statistics in ecology (OCEAN 5052)"
output: html_document
---

## Information

**Time**: Tusday 9:10- 12:10

**Lecturers**: Chih-Hao HSIEH & Yi-Jay CHANG

**Credits**: 3 (including practice)

## Reference

No textbook.  Handouts and primary journal articles will be provided.

## Outline

This is an advanced course intended for senior undergraduate and graduate students with knowledge of basic statistics including random variables, analysis of variance, regression analysis, and rank-based non-parametric statistics. We will discuss several computer-intensive statistical methods. We will discuss the theory, assumption, and application of these methods in ecological problems. The course is designed for hand-on work.  Students need to get familiar with at least one computer language to do the statistics.  Most of work can be done with R or MatLab, but any other programming language will do equally well.  Sometimes, we will use well-developed software when the computation is too complicated and beyond the basic level. There will be dedicated time every week for students to present their works and to discuss the application of these methods on real world problems. 

## Objectives

The objectives are to provide students computational skills for sophisticated statistical methods that are often required for biological questions.

## Schedule (tentative)

Week|Content|Lecturer
----|-------|---------
1|Introduction to R programming and plotting|Yi-Jay CHANG
2|Random variables, distribution, random number generator, statistical identity|Chih-Hao HSIEH
3|Bootstrap and Jackknife|Chih-Hao HSIEH
4|Bootstrapped confidence limits|Chih-Hao HSIEH
5|Permutation|Chih-Hao HSIEH
6|Minimization|Chih-Hao HSIEH
7|
8|Midterm break|NA
9|Classification 1|Yi-Jay CHANG 
10|Classification 2|Yi-Jay CHANG
11|Dimension reduction methods 1 |Yi-Jay CHANG
12|Dimension reduction methods 2 |Yi-Jay CHANG
13|Maximal likelihood |Yi-Jay CHANG
14|Model selection |Yi-Jay CHANG
15|Bayesian analysis I |Yi-Jay CHANG
16|Bayesian analysis II |Yi-Jay CHANG
17|Neural Network |Chih-Hao HSIEH
18|Final discussion (no class)

## Evaluation

Homework 70% + Homework presentation 30%



